feat(kong-ngx-build) hardened build failures on missing OpenResty patches
* Added a fatal warning for visibility when a given patch failed to
  apply
* Added a sanity check ensuring the .patch_applied file was written,
  since there can be other failures in the patching code branch than the
  `patch` command itself. E.g. a failure in the `for` command list, not
  caught by `set -e`, as observed recently in 85b17143 (#17).

diff --git a/kong-ngx-build b/kong-ngx-build
--- a/kong-ngx-build
+++ b/kong-ngx-build
@@ -298,12 +298,17 @@ main() {
             if [ ! -f .patch_applied ]; then
               for patch_file in $(ls -1 $DOWNLOAD_CACHE/openresty-patches/patches/$OPENRESTY_VER/*.patch); do
                 echo "Applying OpenResty patch $patch_file"
-                patch -p1 < $patch_file
+                patch -p1 < $patch_file \
+                  || fatal "failed to apply patch: $patch_file"
               done
 
               touch .patch_applied
             fi
           popd
+
+          if [[ ! -f "bundle/.patch_applied" ]]; then
+            fatal "missing .patch_applied file; some OpenResty patches may not have been applied"
+          fi
         fi
 
         # apply non Kong-specific patches
